# Generated by Django 4.2.11 on 2024-10-25 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacionING', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changehistory',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacionING.activityfolder'),
        ),
        migrations.AddField(
            model_name='projectfolder',
            name='owner',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changehistory',
            name='change_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='changehistory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacionING.projectfolder'),
        ),
    ]
