# Generated by Django 5.1.2 on 2024-11-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionING', '0006_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
