# Generated by Django 4.2.11 on 2024-11-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionING', '0011_changehistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfolder',
            name='priority',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=5),
        ),
    ]
