# Generated by Django 5.1.3 on 2024-11-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionING', '0011_changehistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfolder',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfolder',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
