# Generated by Django 5.1.2 on 2024-11-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionING', '0012_projectfolder_end_date_projectfolder_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfolder',
            name='priority',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=5),
        ),
    ]
